//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisioner) DeepCopyInto(out *EnvironmentProvisioner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisioner.
func (in *EnvironmentProvisioner) DeepCopy() *EnvironmentProvisioner {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentProvisioner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisionerList) DeepCopyInto(out *EnvironmentProvisionerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvironmentProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisionerList.
func (in *EnvironmentProvisionerList) DeepCopy() *EnvironmentProvisionerList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisionerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentProvisionerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisionerSpec) DeepCopyInto(out *EnvironmentProvisionerSpec) {
	*out = *in
	in.ResourcesQuota.DeepCopyInto(&out.ResourcesQuota)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisionerSpec.
func (in *EnvironmentProvisionerSpec) DeepCopy() *EnvironmentProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentProvisionerStatus) DeepCopyInto(out *EnvironmentProvisionerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentProvisionerStatus.
func (in *EnvironmentProvisionerStatus) DeepCopy() *EnvironmentProvisionerStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentProvisionerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesQuota) DeepCopyInto(out *ResourcesQuota) {
	*out = *in
	in.Limits.DeepCopyInto(&out.Limits)
	in.Request.DeepCopyInto(&out.Request)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesQuota.
func (in *ResourcesQuota) DeepCopy() *ResourcesQuota {
	if in == nil {
		return nil
	}
	out := new(ResourcesQuota)
	in.DeepCopyInto(out)
	return out
}
