apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6ImZvbyIsInBhc3N3b3JkIjoiYmFyIiwiYXV0aCI6IlptOXZPbUpoY2c9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: test
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6ImZvbyIsInBhc3N3b3JkIjoiYmFyIiwiYXV0aCI6IlptOXZPbUpoY2c9PSJ9fX0=
kind: Secret
metadata:
  name: regcred-unused
  namespace: test
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test
  namespace: test
---
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test-statefulset
  namespace: test
---
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test-unused
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - image: busybox
        name: init
        command: ["echo"]
        args: ["test"]
        env:
        - name: test
          valueFrom:
            secretKeyRef:
              name: test
              key: foo
      containers:
      - image: busybox
        name: one
        command: ["sleep"]
        args: ["infinity"]
        envFrom:
        - secretRef:
            name: test
      - image: busybox
        name: two
        command: ["sleep"]
        args: ["infinity"]
        env:
        - name: test
          valueFrom:
            secretKeyRef:
              name: test
              key: foo
        volumeMounts:
        - name: foo
          mountPath: "/etc/secret"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - image: busybox
        name: init
        command: ["echo"]
        args: ["test"]
        env:
        - name: test
          valueFrom:
            secretKeyRef:
              name: test-statefulset
              key: foo
      containers:
      - image: busybox
        name: one
        command: ["sleep"]
        args: ["infinity"]
        envFrom:
        - secretRef:
            name: test
      - image: busybox
        name: two
        command: ["sleep"]
        args: ["infinity"]
        env:
        - name: test
          valueFrom:
            secretKeyRef:
              name: test
              key: foo
        volumeMounts:
        - name: foo
          mountPath: "/etc/secret"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: test