helmDefaults:
  wait: true
  waitForJobs: true
  createNamespace: true

repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-cd 
  namespace: argo
  chart: argo/argo-cd
  version: "8.1.2"
  values:
  - dex:
      enabled: false
    notifications:
      enabled: false