apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: otel
spec:
  mode: deployment

  config:
    receivers:
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor
      batch:
        timeout: 5s
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15

    exporters:
      # Traces to Tempo (https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter)
      otlphttp/tempo:
        endpoint: http://tempo.observability.svc.cluster.local:4318
        tls:
          insecure: true
      # Metrics to Prometheus via OTLP HTTP receiver (https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter)
      otlphttp/prometheus:
        endpoint: http://prometheus-server.observability.svc.cluster.local:80/prometheus/api/v1/otlp
        tls:
          insecure: true
      # Logs to Loki (https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter)
      otlphttp/loki:
        endpoint: http://loki.observability.svc.cluster.local:3100/otlp
        tls:
          insecure: true

    service:
      # https://opentelemetry.io/docs/collector/configuration/#service
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/tempo]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/loki]